1. Create a matrix U of shape (m, n) with input values where m and n are input positive integers

In [ ]:
import numpy as np

m = int(input("Enter number of rows (m): "))
n = int(input("Enter number of columns (n): "))

u = []
for i in range(m):
    row = input(f"Enter {n} elements for row {i+1}, separated by spaces: ")
    row_elements = list(map(float, row.strip().split()))
    u.append(row_elements)

U = np.array(u)
print(U)


Enter number of rows (m):  2
Enter number of columns (n):  2
Enter 2 elements for row 1, separated by spaces:  1 2
Enter 2 elements for row 2, separated by spaces:  3 4


[[1. 2.]
 [3. 4.]]


2. Compute X as the transpose of U .

In [ ]:
print("transpose of u is:")
X=U.T
print(X)


transpose of u is:
[[1. 3.]
 [2. 4.]]


3. Create a matrix Y of shape (1, m) with random values ∈ [0, 1]


In [ ]:
Y = np.random.rand(1, m)
print(Y)

[[0.93419463 0.26522306]]


4. Create a matrix W 1 of shape (p, n) with random values ∈ [0, 1] where p is an input


In [ ]:
p=int(input("enter p value:"))
W1=np.random.rand(p,n)
print(W1)

enter p value: 2


[[0.1101886  0.01550452]
 [0.87842457 0.99378785]]


5. Create a vector B1 of shape (p, 1) with random values ∈ [0, 1].


In [ ]:
B1=np.random.rand(p,1)
print(B1)


[[0.75566062]
 [0.95904694]]


6. Create a vector W 2 of shape (1, p) with all zeros


In [ ]:
W2=np.zeros((1,p))
print(W2)

[[0. 0.]]


7. Create a scalar B2 with a random value ∈ [0, 1].


In [ ]:
B2=np.random.rand()
print(B2)

0.8918397872420092



8. Perform the following computations iteratively 15 times:

(a) Z1 = W1 · X + B1 (Matrix Multiplication)

(b) A1 = f(Z1) where f is a function that returns 0 for negative values and the input value itself otherwise.

(c) Z2 = W2 · A1 + B2

(d) A2 = g(Z2) where g(x) = 1 / (1 + e^(−x))

(e) L = ½ · (A2 − Y)²

(f) dA2 = A2 − Y

(g) dZ2 = dA2 ◦ g'(Z2) where g'(x) = g(x) · (1 − g(x)) and ◦ indicates element-wise multiplication

(h) dA1 = W2ᵀ · dZ2

(i) dZ1 = dA1 ◦ f'(Z1) where f'(x) returns 1 for positive values and 0 otherwise

(j) dW1 = (1/m) · dZ1 · Xᵀ

(k) dB1 = (1/m) · ΣdZ1 (sum along the columns)

(l) dW2 = (1/m) · dZ2 · A1ᵀ

(m) dB2 = (1/m) · ΣdZ2 (sum along the columns)

(n) Update and print W1, B1, W2, and B2 for α = 0.01:

* i) W1 = W1 − α · dW1
* ii) B1 = B1 − α · dB1
* iii) W2 = W2 − α · dW2
* iv) B2 = B2 − α · dB2


In [ ]:


# Activation functions
def f(x):  # ReLU
    return np.maximum(0, x)

def fprime(x):
    return (x > 0).astype(float)

def g(x):  # Sigmoid
    return 1 / (1 + np.exp(-x))

def gprime(x):
    s = g(x)
    return s * (1 - s)

# Learning rate
alpha = 0.01
for iteration in range(15):
    # (a) Z1 = W1 · X + B1
    Z1 = W1 @ X + B1  # shape (p, m)

    # (b) A1 = f(Z1)
    A1 = f(Z1)  # ReLU output, shape (p, m)

    # (c) Z2 = W2 · A1 + B2
    Z2 = W2 @ A1 + B2  # shape (1, m)

    # (d) A2 = g(Z2)
    A2 = g(Z2)  # sigmoid output, shape (1, m)

    # (e) L = 1/2 * (A2 - Y)^2 (Loss per sample)
    L = 0.5 * np.square(A2 - Y)  # shape (1, m)

    # (f) dA2 = A2 - Y
    dA2 = A2 - Y  # shape (1, m)

    # (g) dZ2 = dA2 ◦ gprime(Z2)
    dZ2 = dA2 * gprime(Z2)  # element-wise multiplication, shape (1, m)

    # (h) dA1 = W2.T · dZ2
    dA1 = W2.T @ dZ2  # shape (p, m)

    # (i) dZ1 = dA1 ◦ fprime(Z1)
    dZ1 = dA1 * fprime(Z1)  # shape (p, m)

    # (j) dW1 = 1/m · dZ1 · X.T
    dW1 = (1 / m) * dZ1 @ X.T  # shape (p, n)

    # (k) dB1 = 1/m * sum of dZ1 along columns
    dB1 = (1 / m) * np.sum(dZ1, axis=1, keepdims=True)  # shape (p, 1)

    # (l) dW2 = 1/m · dZ2 · A1.T
    dW2 = (1 / m) * dZ2 @ A1.T  # shape (1, p)

    # (m) dB2 = 1/m * sum of dZ2 along columns
    dB2 = (1 / m) * np.sum(dZ2, axis=1, keepdims=True)  # shape (1, 1), scalar but kept as array

    W1 -= alpha * dW1
    B1 -= alpha * dB1
    W2 -= alpha * dW2
    B2 -= alpha * dB2.item()  # Convert to scalar

    # Print updated parameters
    print(f"Iteration {iteration + 1}:")
    print("W1:\n", W1)
    print("B1:\n", B1)
    print("W2:", W2)
    print("B2:", B2)
    print("Loss:", np.mean(L))
    print("-" * 40)

Iteration 1:
W1:
 [[0.11022705 0.01554946]
 [0.87874421 0.99416136]]
B1:
 [[0.75566711]
 [0.95910082]]
W2: [[-0.00458172 -0.03874977]]
B2: 0.8887463206564279
Loss: 0.05289555064760101
----------------------------------------
Iteration 2:
W1:
 [[0.11023172 0.01555482]
 [0.8787837  0.99420672]]
B1:
 [[0.7556678 ]
 [0.95910669]]
W2: [[-0.00482665 -0.04095404]]
B2: 0.8885949345869967
Loss: 0.05239097088872216
----------------------------------------
Iteration 3:
W1:
 [[0.11023659 0.0155604 ]
 [0.87882501 0.994254  ]]
B1:
 [[0.75566851]
 [0.95911266]]
W2: [[-0.0050661  -0.04312849]]
B2: 0.8884489795582825
Loss: 0.05189980163895261
----------------------------------------
Iteration 4:
W1:
 [[0.11024164 0.01556617]
 [0.87886806 0.99430312]]
B1:
 [[0.75566922]
 [0.95911872]]
W2: [[-0.00530001 -0.04527265]]
B2: 0.8883085038779446
Loss: 0.051422085498038575
----------------------------------------
Iteration 5:
W1:
 [[0.11024688 0.01557212]
 [0.87891277 0.99435393]]
B1:
 [[0.75566994]
 [0.9591248